FROM node:20-alpine

WORKDIR /app

COPY edysync/package*.json edysync/angular.json edysync/tsconfig*.json edysync/.postcssrc.json ./

RUN npm ci --legacy-peer-deps

EXPOSE 4200

CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--poll", "2000"]
