"""initial_schema

Revision ID: bba7eaa6929b
Revises:
Create Date: 2026-06-04 15:39:34.288860

"""

# revision identifiers, used by Alembic.
revision = 'bba7eaa6929b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
