from app.models.user import *
from app.models.payment import *
from app.models.appointment import *
from app.models.game import *
from app.models.notification import *
from app.models.chat import *
from app.models.report import *
from app.models.admin import *
from app.models.ai import *
